VehicleDelivery/VehicleDelivery/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change_passwd/', PasswordChangeView.as_view(template_name='registration/passwd_change.html', success_url="/change_passwd_done/"), name='change_passwd'),
    path('change_passwd_done/', PasswordChangeDoneView.as_view(template_name='registration/passwd_change_done.html'), name='change_passwd_done'),
    path('', include("main.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VehicleDelivery/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path("thanks/", views.thanks, name="thanks"),
    path("form_claim/", views.form_claim, name="form_claim"),
    path("forms/", views.form_all, name="form_all"),
    path("departments/", views.departments, name="departments"),
    path("form_department/<int:id>/", views.form_update_department, name="form_department"),
    path("create_department/", views.form_create_department, name="create_department"),
    path("create_person/", views.form_create_person, name="create_person"),
    path("users/", views.users, name="users"),
    path("change_passwd/<int:id>/", views.form_change_person_passwd, name="change_passwd"),
    path("update_person/<int:id>/", views.form_update_person, name="update_person"),
    path("form_transportation/", views.form_transport, name="form_transportation"),
    path("form_preparation/", views.form_preparation, name="form_preparation"),
    path("form_communication/", views.form_communication, name="form_communication"),
    path("form_other/", views.form_other, name="form_other"),
    path("no_access/", views.no_access, name="no_access"),
    path("agent_dashboard/", views.agent_dashboard, name="agent_dashboard"),
    path("entry_detail/<int:id>/<str:_type>", views.entry_detail, name="entry_detail"),
    path('update_status/', views.update_status, name='update_status'),
    path('switch-language/<str:language_code>/', views.switch_language, name='switch_language'),
    path("statistics", views.statistics, name="statistics"),
    path("logs", views.logs, name="logs")
]

VehicleDelivery/main/models.py
from django.db import models
from django.utils.timezone import now
from datetime import date
import datetime
from .dropdown_options import NATURE_OF_DAMAGE, PLACE_OF_DAMAGE, STATUS_CHOICES, REPORT_TYPES, TYPE_OF_USER
import os
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.


class Department(models.Model):
    # code = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(default=None, null=True)
    reclamationType = models.CharField(max_length=3, choices=REPORT_TYPES, default='OT', blank=False)

    def __str__(self):
        return self.name

class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    # category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    user_type = models.CharField(max_length=5, choices=TYPE_OF_USER, default='AGENT')
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.user.username} ({self.user_type})"





class ClaimModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    #Udaje o strane nahlasujuceho
    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()

    #Udaje o preprave
    record_number = models.CharField(max_length=30)
    registration_number = models.CharField(max_length=30)
    date = models.DateField(null=True, blank=True, default=datetime.date.today)
    country_of_arrival = models.CharField(max_length=30)
    place_of_arrival = models.CharField(max_length=30)
    city_of_arrival = models.CharField(max_length=30)


    #Podrobnosti o poskodenom vozidle
    VIN_number = models.CharField(max_length=30)
    nature_of_damage_1 = models.CharField(max_length=30, choices=NATURE_OF_DAMAGE, default='XX')
    place_of_damage_1 = models.CharField(max_length=30, choices=PLACE_OF_DAMAGE, default='00')
    nature_of_damage_2 = models.CharField(max_length=30, choices=NATURE_OF_DAMAGE, default='XX')
    place_of_damage_2 = models.CharField(max_length=30, choices=PLACE_OF_DAMAGE, default='00')
    nature_of_damage_3 = models.CharField(max_length=30, choices=NATURE_OF_DAMAGE, default='XX')
    place_of_damage_3 = models.CharField(max_length=30, choices=PLACE_OF_DAMAGE, default='00')


    #Poznamka
    message = models.TextField()

    #Subory
    waybill = models.FileField(upload_to='temp/')
    damage_report = models.FileField(upload_to='temp/')
    photo_car = models.FileField(upload_to='temp/')
    photo_VIN = models.FileField(upload_to='temp/')
    photo_area = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/CL', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.waybill, "waybill"),
            (self.damage_report, "damage_report"),
            (self.photo_car, "photo_car"),
            (self.photo_VIN, "vin_number"),
            (self.photo_area, "photo_area"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/CL', folder_name, new_file_name)
        super().save(*args, **kwargs)

class OtherModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/OT', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/OT', folder_name, new_file_name)
        super().save(*args, **kwargs)

class TransportModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Podrobnosti o vozidle
    VIN_number = models.CharField(max_length=30)
    vehicle_model = models.CharField(max_length=30)
    registration_number = models.CharField(max_length=30)


    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')


    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')

    # def get_type(self):
    #     return "Transport"
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/TR', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/TR', folder_name, new_file_name)
        super().save(*args, **kwargs)

class CommunicationModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/CM', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/CM', folder_name, new_file_name)
        super().save(*args, **kwargs)

class PreparationModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Podrobnosti o vozidle
    VIN_number = models.CharField(max_length=30)
    vehicle_model = models.CharField(max_length=30)

    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/VP', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/VP', folder_name, new_file_name)
        super().save(*args, **kwargs)

VehicleDelivery/main/templates/departments/department_form.html
{% extends "base_agent.html" %}
{% block title %}Departments Form{% endblock %}

{% load i18n %}
{% block content %}
<style>
    form {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 15px;
    width: 100%;
}
</style>
<!--
    <h1>Departments Form</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="save" value="save">{% trans "Save" %}</button>
    </form>
    <form method="post">
        {% csrf_token %}
        <button class="danger" type="submit" name="delete" value="delete">{% trans "Delete" %}</button>
    </form>
-->


<div class="centered-container">
    <h1>{% trans "Departments Form" %}</h1>
    <form method="post" class="departments-form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        {% if creating_new %}
        <button type="submit" name="save" value="save" class="primary-button">{% trans "Create" %}</button>
        {% else %}
        <button type="submit" name="save" value="save" class="primary-button">{% trans "Save" %}</button>
        {% endif %}

    </form>

    <form method="post" class="delete-form">
        {% csrf_token %}
        {% if not creating_new %}
        <button type="submit" name="delete" value="delete" class="danger-button">{% trans "Delete" %}</button>
        {% endif %}
    </form>
</div>

{% endblock %}

VehicleDelivery/main/templates/departments/departments.html
{% extends "base_agent.html" %}
{% block title %}Departments List{% endblock %}
{% load i18n %}

{% block content %}
<style>
    form {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 15px;
    width: 100%;
    }

    .search-form {
    margin-top: 100px;
    justify-content: center;
    gap: 10px;
    margin-bottom: 20px;
    }

    .search-button {
    color: black;
    width: 50%;
    padding: 10px;
    font-size: 16px;
    }

    .primary-button {
    background: #007bff;
    color: white;
    width: 90%;
    padding: 10px;
    font-size: 16px;
    }

    .search-form input {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    font-size: 16px;
    width: 90%;
    }
</style>
<!---
<h1>{% trans "Departments" %}:</h1>
<form method="post">
    {% csrf_token %}
    <button type="submit" name="add" value="add">{% trans "Add Department" %}</button>
    <ul>
        {% for department in departments %}
        <li>
            <button type="submit" name="department" value={{department.id}}>
                {% if department.name %}
                {{ department.name }}
                {% else %}
                No Name
                {% endif %}
            </button></li>
            {% endfor %}
        </ul>
    </form>
-->

<div class="centered-container">
    <h1>{% trans "Departments" %}</h1>

    <form method="get" action="/create_department">
        <button type="submit" class="primary-button">{% trans "Add Department" %}</button>
    </form>


    <form method="get" class="search-form">
        <input type="text" name="search" placeholder="{% trans 'Search...' %}"><!--value="{{ search_query }}"-->
        <button type="submit" class="search-button">{% trans "Search" %}</button>
    </form>

    <form method="post" class="departments-form">
        {% csrf_token %}
        <ul class="department-list">
            {% for department in departments %}
                <li class="department_li">
                    <button type="submit" name="department" value="{{ department.id }}" class="department-button">
                        {% if department.name %}
                            {{ department.name }}
                            <br>

                            {{ department.reclamationType }} - {{department.get_reclamationType_display}}
                        {% else %}
                            No Name
                        {% endif %}
                    </button>
                </li>
            {% empty %}
                <li>
                    {% trans "No Results" %}
                </li>
            {% endfor %}
        </ul>
    </form>
</div>


{% endblock %}