VehicleDelivery/VehicleDelivery/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change_passwd/', PasswordChangeView.as_view(template_name='registration/passwd_change.html', success_url="/change_passwd_done/"), name='change_passwd'),
    path('change_passwd_done/', PasswordChangeDoneView.as_view(template_name='registration/passwd_change_done.html'), name='change_passwd_done'),
    path('', include("main.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VehicleDelivery/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path("thanks/", views.thanks, name="thanks"),
    path("form_claim/", views.form_claim, name="form_claim"),
    path("forms/", views.form_all, name="form_all"),
    path("departments/", views.departments, name="departments"),
    path("form_department/<int:id>/", views.form_update_department, name="form_department"),
    path("create_department/", views.form_create_department, name="create_department"),
    path("create_person/", views.form_create_person, name="create_person"),
    path("users/", views.users, name="users"),
    path("change_passwd/<int:id>/", views.form_change_person_passwd, name="change_passwd"),
    path("update_person/<int:id>/", views.form_update_person, name="update_person"),
    path("form_transportation/", views.form_transport, name="form_transportation"),
    path("form_preparation/", views.form_preparation, name="form_preparation"),
    path("form_communication/", views.form_communication, name="form_communication"),
    path("form_other/", views.form_other, name="form_other"),
    path("no_access/", views.no_access, name="no_access"),
    path("agent_dashboard/", views.agent_dashboard, name="agent_dashboard"),
    path("entry_detail/<int:id>/<str:_type>", views.entry_detail, name="entry_detail"),
    path('update_status/', views.update_status, name='update_status'),
    path('switch-language/<str:language_code>/', views.switch_language, name='switch_language'),
    path("statistics", views.statistics, name="statistics"),
    path("logs", views.logs, name="logs")
]

VehicleDelivery/main/models.py
from django.db import models
from django.utils.timezone import now
from datetime import date
import datetime
from .dropdown_options import NATURE_OF_DAMAGE, PLACE_OF_DAMAGE, STATUS_CHOICES, REPORT_TYPES, TYPE_OF_USER
import os
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.


class Department(models.Model):
    # code = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(default=None, null=True)
    reclamationType = models.CharField(max_length=3, choices=REPORT_TYPES, default='OT', blank=False)

    def __str__(self):
        return self.name

class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    # category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    user_type = models.CharField(max_length=5, choices=TYPE_OF_USER, default='AGENT')
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.user.username} ({self.user_type})"





class ClaimModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    #Udaje o strane nahlasujuceho
    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()

    #Udaje o preprave
    record_number = models.CharField(max_length=30)
    registration_number = models.CharField(max_length=30)
    date = models.DateField(null=True, blank=True, default=datetime.date.today)
    country_of_arrival = models.CharField(max_length=30)
    place_of_arrival = models.CharField(max_length=30)
    city_of_arrival = models.CharField(max_length=30)


    #Podrobnosti o poskodenom vozidle
    VIN_number = models.CharField(max_length=30)
    nature_of_damage_1 = models.CharField(max_length=30, choices=NATURE_OF_DAMAGE, default='XX')
    place_of_damage_1 = models.CharField(max_length=30, choices=PLACE_OF_DAMAGE, default='00')
    nature_of_damage_2 = models.CharField(max_length=30, choices=NATURE_OF_DAMAGE, default='XX')
    place_of_damage_2 = models.CharField(max_length=30, choices=PLACE_OF_DAMAGE, default='00')
    nature_of_damage_3 = models.CharField(max_length=30, choices=NATURE_OF_DAMAGE, default='XX')
    place_of_damage_3 = models.CharField(max_length=30, choices=PLACE_OF_DAMAGE, default='00')


    #Poznamka
    message = models.TextField()

    #Subory
    waybill = models.FileField(upload_to='temp/')
    damage_report = models.FileField(upload_to='temp/')
    photo_car = models.FileField(upload_to='temp/')
    photo_VIN = models.FileField(upload_to='temp/')
    photo_area = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/CL', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.waybill, "waybill"),
            (self.damage_report, "damage_report"),
            (self.photo_car, "photo_car"),
            (self.photo_VIN, "vin_number"),
            (self.photo_area, "photo_area"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/CL', folder_name, new_file_name)
        super().save(*args, **kwargs)

class OtherModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/OT', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/OT', folder_name, new_file_name)
        super().save(*args, **kwargs)

class TransportModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Podrobnosti o vozidle
    VIN_number = models.CharField(max_length=30)
    vehicle_model = models.CharField(max_length=30)
    registration_number = models.CharField(max_length=30)


    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')


    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')

    # def get_type(self):
    #     return "Transport"
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/TR', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/TR', folder_name, new_file_name)
        super().save(*args, **kwargs)

class CommunicationModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/CM', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/CM', folder_name, new_file_name)
        super().save(*args, **kwargs)

class PreparationModel(models.Model):
    date_of_arrival = models.DateField(auto_now_add=True)

    firm_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    email = models.EmailField()
    date = models.DateField(null=True, blank=True, default=datetime.date.today)

    #Podrobnosti o vozidle
    VIN_number = models.CharField(max_length=30)
    vehicle_model = models.CharField(max_length=30)

    #Poznamka
    message = models.TextField()

    #Subory
    photo = models.FileField(upload_to='temp/')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        folder_name = str(self.id)
        new_folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads/VP', folder_name)

        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        file_fields = [
            (self.photo, "file"),
        ]

        for file, new_name in file_fields:
            if file and os.path.exists(file.path):
                old_path = file.path
                file_extension = os.path.splitext(old_path)[1]
                new_file_name = f"{new_name}{file_extension}"
                new_file_path = os.path.join(new_folder_path, new_file_name)

                os.rename(old_path, new_file_path)

                file.name = os.path.join('uploads/VP', folder_name, new_file_name)
        super().save(*args, **kwargs)

VehicleDelivery/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'FormsCss.css' %}">
</head>

<style>

</style>

<body>
    <header>
        <nav class="navbar">
            <div class="navbar-left">
                <a href="{% url 'home' %}">
                    <img src="{% static 'images/LOGO.png' %}" alt="Your Logo" style="height: 25px;">
                </a>
            </div>
            <ul class="navbar-links">
                <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
                <li><a href="{% url 'form_all' %}">{% trans "Reports" %}</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'agent_dashboard' %}">{% trans "Agent Zone" %}</a></li>
                {% endif %}
            </ul>
            <div class="language-switcher">
                <button class="dropdown-btn" onclick="toggleDropdown()">
                    {% if LANGUAGE_CODE == 'en' %} EN {% elif LANGUAGE_CODE == 'sk' %} SK {% endif %}
                    ▼
                </button>
                <div class="dropdown-menu">
                    <a href="{% url 'switch_language' 'en' %}" class="{% if LANGUAGE_CODE == 'en' %}active{% endif %}">EN</a>
                    <a href="{% url 'switch_language' 'sk' %}" class="{% if LANGUAGE_CODE == 'sk' %}active{% endif %}">SK</a>
                </div>
            </div>
            <div class="navbar-login">
                {% if user.is_authenticated %}
                <!--
                <form class="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="login-button" type="submit">{% trans "Logout" %}</button>
                </form>
                -->
                    <a href="#" class="login-button" onclick="document.getElementById('logout-form').submit();">
                        {% trans "Logout" %}
                    </a>

                    <form id="logout-form" class="logout-form" method="post" action="{% url 'logout' %}" style="display: none;">
                        {% csrf_token %}
                    </form>
                {% else %}
                    <a href="{% url 'login' %}" class="login-button">{% trans "Login" %}</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <script>
        function toggleDropdown() {
            const dropdownMenu = document.querySelector('.dropdown-menu');
            dropdownMenu.style.display = dropdownMenu.style.display === 'block' ? 'none' : 'block';
        }
    </script>
    {% block content %}
    <!-- Content will go here -->
    {% endblock %}

    <footer>
        <div class="footer-content">
            <p>&copy; 2024 Formular Inc. | All Rights Reserved</p>
            <p>Designed by Your Name</p>
        </div>
    </footer>
</body>
</html>

VehicleDelivery/main/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact Page{% endblock %}

{% block content %}
<h1>{% trans "This is an contact page" %}</h1>
<p>-</p>
{% endblock %}

VehicleDelivery/main/templates/entry_detail.html
{% extends "base_agent.html" %}
{% block title %}Departments List{% endblock %}
{% load i18n %}

{% block content %}

<style>
/* Container Styling */
.details-container {
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    max-width: 60%;
    margin: 30px auto;
    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
    color: #001f3f;
}

/* Header Styling */
.details-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 2px solid #007bff;
    padding-bottom: 10px;
    margin-bottom: 20px;
}

.details-header h1 {
    margin: 0;
    font-size: 24px;
    color: #001f3f;
}

/* Back Button */
.back-button {
    background-color: #007bff;
    color: white;
    text-decoration: none;
    font-weight: bold;
    padding: 8px 12px;
    border-radius: 5px;
    transition: background 0.3s, color 0.3s;
}

.back-button:hover {
    background-color: #0056b3;
}

/* Content Styling */
.details-content {
    display: grid;
    grid-template-columns: 1fr 1fr; /* Two columns */
    gap: 10px;
}

/* Individual Detail Item */
.detail-item {
    display: flex;
    justify-content: space-between;
    background-color: #e3f2fd; /* Light blue */
    padding: 10px;
    border-radius: 5px;
    border-left: 4px solid #007bff;
}

.detail-item label {
    font-weight: bold;
    color: #001f3f;
}

.detail-item span {
    color: #003366;
    font-weight: normal;
}

.message-item {
    grid-column: span 2; /* Makes the message span across both columns */
    background-color: #e3f2fd; /* Light blue */
    padding: 15px;
    border-radius: 5px;
    border-left: 4px solid #007bff;
    display: flex;
    flex-direction: column;
    gap: 5px;
}

</style>

    <div class="details-container">
        <div class="details-header">
            <h1>{% trans "Report Details" %}</h1>
            <a href="{% url 'agent_dashboard' %}" class="back-button">{% trans "Back to Dashboard" %}</a>
            <form method="post">
                {% csrf_token %}
                <button type="submit" name="export">📥 Export to Excel</button>
            </form>
            <form method="post">
                {% csrf_token %}
                <button type="submit" name="download" class="download-all-button">📦 Download All Files</button>
            </form>
        </div>
        

        <div class="details-content">
            <div class="detail-item">
                <label for="entry-id">{% trans "Entry ID" %}:</label>
                <span id="entry-id">{{ entry.id }}</span>
            </div>

            <div class="detail-item">
                <label for="entry-status"> {% trans "Status" %}:</label>
                <span id="entry-status">{{ entry.status }}</span>
            </div>
            {% if entry.date_of_arrival %}
            <div class="detail-item">
                <label for="entry-date-of-arrival">{% trans "Recieved" %}</label>
                <span id="entry-date-of-arrival">{{ entry.date_of_arrival}}</span>
            </div>
            {% endif %}


            <div></div>
            <div><h3>{% trans "Details of Reporting Party" %}<h3></div><!--------------------------------------------------------------------------------------------------->
            <div></div>
            <div class="detail-item">
                <label for="entry-name">{% trans "Firm name" %}</label>
                <span id="entry-name">{{ entry.firm_name}}</span>
            </div>
            <div class="detail-item">
                <label for="entry-name">{% trans "First Name" %}</label>
                <span id="entry-name">{{ entry.first_name }}</span>
            </div>
            <div class="detail-item">
                <label for="entry-email">{% trans "Email" %}:</label>
                <span id="entry-email">{{ entry.email }}</span>
            </div>
            <div class="detail-item">
                <label for="entry-name">{% trans "Last Name" %}</label>
                <span id="entry-name">{{ entry.second_name }}</span>
            </div>


            <div></div><div></div>
            <div><h3>{% trans "Transport Details" %}<h3></div><!--------------------------------------------------------------------------------------------------->
            <div></div>
            {% if entry.record_number %}
            <div class="detail-item">
                <label for="entry-rec_num">{% trans "Record Number" %}</label>
                <span id="entry-rec_num">{{ entry.record_number }}</span>
            </div>
            {% endif %}
            {% if entry.registration_number %}
            <div class="detail-item">
                <label for="entry-reg_num">{% trans "Registration Number" %}</label>
                <span id="entry-reg_num">{{ entry.registration_number }}</span>
            </div>
            {% endif %}
            {% if entry.date %}
            <div class="detail-item">
                <label for="entry-date">{% trans "Date of arrival" %}</label>
                <span id="entry-date">{{ entry.date }}</span>
            </div>
            {% endif %}
            {% if entry.country_of_arrival %}
            <div class="detail-item">
                <label for="entry-country">{% trans "Country of Arrival" %}</label>
                <span id="entry-country">{{ entry.country_of_arrival }}</span>
            </div>
            {% endif %}
            {% if entry.place_of_arrival %}
            <div class="detail-item">
                <label for="entry-place">{% trans "Place of Arrival" %}</label>
                <span id="entry-place">{{ entry.place_of_arrival }}</span>
            </div>
            {% endif %}
            {% if entry.city_of_arrival %}
            <div class="detail-item">
                <label for="entry-city">{% trans "City of Arrival" %}</label>
                <span id="entry-city">{{ entry.city_of_arrival }}</span>
            </div>
            {% endif %}




            {% if entry.VIN_number %}
            <div></div>
            <div><h3>{% trans "Vehicle Damage Details" %}<h3></div><!--------------------------------------------------------------------------------------------------->
            {% endif %}
            <div></div>
            {% if entry.VIN_number %}
            <div class="detail-item">
                <label for="entry-city">{% trans "VIN number" %}</label>
                <span id="entry-city">{{ entry.VIN_number }}</span>
            </div>
            {% endif %}
            <div></div>

            {% if entry.vehicle_model %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Vehicle Model" %}</label>
                <span id="entry-city">{{ entry.vehicle_model }}</span>
            </div>
            {% endif %}





            {% if entry.nature_of_damage_1 %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Nature of Damage" %}</label>
                <span id="entry-city">{{ entry.nature_of_damage_1 }}   {{ entry.get_nature_of_damage_1_display }}</span>
            </div>
            {% endif %}
            {% if entry.place_of_damage_1 %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Place of Damage" %}</label>
                <span id="entry-city">{{ entry.place_of_damage_1 }}   {{ entry.get_place_of_damage_1_display }}</span>
            </div>
            {% endif %}
            {% if entry.nature_of_damage_2 %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Nature of Damage" %}</label>
                <span id="entry-city">{{ entry.nature_of_damage_2 }}   {{ entry.get_nature_of_damage_2_display }}</span>
            </div>
            {% endif %}
            {% if entry.place_of_damage_2 %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Place of Damage" %}</label>
                <span id="entry-city">{{ entry.place_of_damage_2 }}   {{ entry.get_place_of_damage_2_display }}</span>
            </div>
            {% endif %}
            {% if entry.nature_of_damage_3 %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Nature of Damage" %}</label>
                <span id="entry-city">{{ entry.nature_of_damage_3 }}   {{ entry.get_nature_of_damage_3_display }}</span>
            </div>
            {% endif %}
            {% if entry.place_of_damage_3 %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Place of Damage" %}</label>
                <span id="entry-city">{{ entry.place_of_damage_3 }}   {{ entry.get_place_of_damage_3_display }}</span>
            </div>
            {% endif %}


            <div></div><div></div>
            <div><h3>{% trans "Note" %}<h3></div><!--------------------------------------------------------------------------------------------------->
            <div></div>
            <div class="detail-item message-item">
                <label for="entry-message">{% trans "Message" %}:</label>
                <span id="entry-message">{{ entry.message }}</span>
            </div>


            <div></div><div></div>
            <div><h3>{% trans "Files" %}<h3></div><!--------------------------------------------------------------------------------------------------->
            <div></div>
            {% if entry.photo %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Photo" %}</label>
                <a id="entry-document" href="{{ entry.photo.url }}" download>
                    {% trans "Download" %}
                </a>
            </div>
            {% endif %}
            {% if entry.waybill %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Waybill" %}</label>
                <a id="entry-document" href="{{ entry.waybill.url }}" download>
                    {% trans "Download" %}
                </a>
            </div>
            {% endif %}
            {% if entry.damage_report %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Damage Report" %}</label>
                <a id="entry-document" href="{{ entry.damage_report.url }}" download>
                    {% trans "Download" %}
                </a>
            </div>
            {% endif %}
            {% if entry.photo_car %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Photo of Car" %}</label>
                <a id="entry-document" href="{{ entry.photo_car.url }}" download>
                    {% trans "Download" %}
                </a>
            </div>
            {% endif %}
            {% if entry.photo_VIN %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Phot of VIN number" %}</label>
                <a id="entry-document" href="{{ entry.photo_VIN.url }}" download>
                    {% trans "Download" %}
                </a>
            </div>
            {% endif %}
            {% if entry.photo_area %}
            <div class="detail-item">
                <label for="entry-city">{% trans "Phot of Damaged Area" %}</label>
                <a id="entry-document" href="{{ entry.photo_area.url }}" download>
                    {% trans "Download" %}
                </a>
            </div>
            {% endif %}
    </div>
    {% endblock %}

VehicleDelivery/main/templates/form_other.html
{% extends "base.html" %}

{% block title %}Form Other{% endblock %}
{% load static %}
{% load i18n %}
<link rel="stylesheet" href="{% static 'FormsCss.css' %}">
{% block content %}
    <main>
        <h1>{% trans "Other" %}</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h3 style="font-size: 24px; color: #505050; text-decoration: underline; margin-bottom: 10px;">{% trans "Details of Reporting Party" %}</h3><h3></h3>
            <div>
                <label for="{{ form.firm_name.id_for_label }}">{% trans "Firm name" %}</label>
                {{ form.firm_name }}
            </div>
            <div>
                <label for="{{ form.second_name.id_for_label }}">{% trans "Second name" %}</label>
                {{ form.second_name }}
            </div>
            <div>
                <label for="{{ form.first_name.id_for_label }}">{% trans "First name" %}</label>
                {{ form.first_name }}
            </div>
            <div>
                <label for="{{ form.email.id_for_label }}">{% trans "E-mail" %}</label>
                {{ form.email }}
            </div>
            <div>
                <label for="{{ form.date.id_for_label }}">{% trans "Date" %}</label>
                {{ form.date }}
            </div>
            <div> </div>



            <h3 style="font-size: 24px; color: #505050; text-decoration: underline; margin-bottom: 10px;">{% trans "Note" %}</h3><h3></h3>
            <div style="grid-column: span 2;
            display: flex;
            justify-content: center;
            height: 100px;
            align-items: center;
            color: white;
            font-size: 18px;
            text-align: center;">
                {{ form.message }}
            </div>


            <h3 style="font-size: 24px; color: #505050; text-decoration: underline; margin-bottom: 10px;">{% trans "Files" %}</h3><h3></h3>
            <div>
                <label for="{{ form.photo.id_for_label }}">{% trans "File" %}</label>
                {{ form.photo }}
            </div>

            <div class="submit-container">
                <button type="submit" class="submit-button">{% trans "Submit" %}</button>
            </div>
        </form>
    </main>
{% endblock %}

VehicleDelivery/main/templates/home.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
<a href="{% url 'form_all' %}" class="letter-image">
    <div class="animated-mail">
        <div class="back-fold"></div>
        <div class="letter">
            <div class="letter-border"></div>
            <div class="letter-title"></div>
            <div class="letter-context"></div>
            <div class="letter-stamp">
                <div class="letter-stamp-inner"></div>
            </div>
        </div>
        <div class="top-fold"></div>
        <div class="body"></div>
        <div class="left-fold"></div>
    </div>
    <div class="shadow"></div>
</a>
{% endblock %}